### ISSUE TITLE
Overriding the templates provided as a part of the library

### ISSUE THREAD

**Issue by jaischeema** [elixirdrops/carbon#1]
Do you know any easy way I can use custom templates for the login/register?

**Comment by allyraza** [comment]
I am in process of writing generators for customizing carbon, I am having problems with local erlang installation for past 1 week now, okay back to your question to customize the templates, you have to overwrite the controller,view and templates
1. copy session,user controller from carbon to your controllers dir
2. move view files and templates
3. change the routes in route to point to your new controllers

```
# login
get /login, SessionController, :new
post /login, SessionController, :create
# registeration
get /register, UserController, :new
post /register, UserController, :create
```

**Comment by jaischeema** [comment]
Thank you for the quick reply, doing awesome work 😄

**Comment by allyraza** [comment]
thank you
